version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: gbt_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_store
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database_schema.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - gbt_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gbt_backend
    restart: always
    environment:
      PORT: 5000
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: my_store
      JWT_SECRET: 6f650fec6eb2a4748ae921cda6ff0546391aa2f34c9625aa27da3444798220f3cd125810ebf5553da711f7faeccd4be219dba7ae4f65db8b7835226dce72d19e
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - gbt_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: gbt_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - gbt_network

volumes:
  mysql_data:

networks:
  gbt_network:
    driver: bridge
